version: '4.2.0'
services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/Entregable4
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql: 5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 